name: Generate Datas

on:
schedule: # execute every 12 hours - cron: "\* _/12 _ \* \*"
workflow_dispatch:

jobs:
build:
name: Formandodev
runs-on: ubuntu-latest
steps: # Snake Animation - uses: Platane/snk@master
id: snake-gif
with:
github_user_name: Formandodev
svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

